### ISSUE TITLE
Built in gkey disabling

### ISSUE THREAD

**Issue by ShayBox** [JSubelj/g910-gkey-macro-support#2]
It's quite annoying to have to use another program for this one to work, so here's the c++ code I pulled out of g810-led to disable GKeys on g910 keyboards (that's the only one g810-led worked on), you probably wouldn't use this code in your project, but it should be simple enough that you could figure it out and re-write it in python, It only contains the libusb code while g810-led also supports hidapi, as hidapi rarely works and in the case of a one-time use disabling function the speed improvement is negligible over libusb which will always work.  
[GKeys.zip](https://github.com/JSubelj/g910-gkey-macro-support/files/2692265/GKeys.zip)

**Comment by JSubelj** [comment]
Hi, thank you very much for putting thought and effort into my driver. I will certainly look this up when I have a bit more time. Till then thank you again and sorry for late response.

**Comment by JSubelj** [comment]
I figured out how to disable GKey to FKey mapping and its out in the RELEASE-0.2.0. Try it out.
Thank you very much for the code so I didn't have to dwell in g810-led repo, it helped a lot.
 If you have any problems you are welcome to write about it here (same topic) or open a new issue request. Have fun.
