### ISSUE TITLE
[Misc] Sidewinderd - similar project

### ISSUE THREAD

**Issue by cornernote** [JSubelj/g910-gkey-macro-support#21]
Hey.  I think you looked at sidewinderd before starting this project.  

I used it on my G105 keyboard for years and it was great.  It has full support for recording and playback of macros using the M-Keys, MR and G-Keys.  

I have managed to get it working with my G815 keyboard, which is similar to the G910, and thought you may be interested.  Here is my PR for G815 - https://github.com/tolga9009/sidewinderd/pull/41/files

**Comment by JSubelj** [comment]
Hey thanks for your input, will definitely check it out. And if I find some time maybe implement g910 into it. Will see.

Have fun,

Jan
