### ISSUE TITLE
[Issue] Service does not install on linux-mint 19.3

### ISSUE THREAD

**Issue by ajpirciovs** [JSubelj/g910-gkey-macro-support#27]
**Describe the bug**
After running installer.sh a service file exists in the installation directory but is NOT copied over to /etc/systemd/system. The documentation refers to /usr/lib/systemd/system/g910-gkeys.service which is not the correct folder in this distro 

**To Reproduce**
1. Go thru install steps on linix-mint 19.3 (or probably ubuntu as well)
2. See that service file is not present where indicated

**Expected behavior**
Should detect system service file location path and copy appropriately

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3 Tricia
 - Kernel version: Linux Mint 19.3 Tricia
 - python version: 3.7.4

**Comment by ajpirciovs** [comment]
I would like to add that this is a great utility and I thank you much!

**Comment by braoult** [comment]
This one should be fixed after #36 . I think this case can be closed.
