### ISSUE TITLE
**BEWARE** Wipes all services on Ubuntu 20.04

### ISSUE THREAD

**Issue by bcvery1** [JSubelj/g910-gkey-macro-support#33]
**Describe the bug**
Followed the instructions on README.md, has overwritten the `/usr/lib/systemd/system` with the `g910-gkeys.service` file.  All service files from the PC are gone.

**To Reproduce**
1. On Ubuntu 20.04, follow the instructions.

**Expected behavior**
Does not overwrite all system services.

**Screenshots**
```sh
$ ll /usr/lib/systemd
total 60
drwxr-xr-x  10 root root  4096 Jun  2 09:13 ./
drwxr-xr-x 135 root root 12288 May 31 14:37 ../
drwxr-xr-x   3 root root  4096 Jul 25  2018 boot/
drwxr-xr-x   2 root root  4096 May 10 14:58 catalog/
drwxr-xr-x   2 root root  4096 May 10 15:05 logind.conf.d/
-rw-r--r--   1 root root   230 Jun  2 09:13 system
drwxr-xr-x   2 root root  4096 May 10 14:58 system-environment-generators/
drwxr-xr-x  10 root root 12288 May 21 13:39 user/
drwxr-xr-x   2 root root  4096 May 10 15:02 user-environment-generators/
drwxr-xr-x   2 root root  4096 Apr 20  2018 user-generators/
drwxr-xr-x   2 root root  4096 May 10 14:58 user-preset/
```

```sh
$ cat /usr/lib/systemd/system
[Unit]
Description=Support for Logitech g910 keyboard gkeys
Documentation=https://github.com/JSubelj/g910-gkey-macro-support/wiki

[Service]
ExecStart=/usr/bin/env g910-gkeys
TimeoutStopSec=3


[Install]
WantedBy=multi-user.target
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Kernel version: 5.4.0-33-generic
 - desktop enviroment: Gnome
 - g910-gkeys version: master from github
 - python version: 2.7.18rc1

**Comment by JSubelj** [comment]
Hey, 

I'm so sorry to hear that. That's really and I mean REALLY weird behavior of cp command. I'm gonna patch it right away. Really sorry for this.

Btw, you need Python version >=3.7 to run the driver.

Again really sorry.
