### ISSUE TITLE
Add support for "sleep" in shortcuts

### ISSUE THREAD

**Issue by stevendesu** [JSubelj/g910-gkey-macro-support#50]
I'm interested in creating a macro that presses a key, waits a few seconds, then presses another key. Reading through the source for the G910 key tool you created it seems like the only way to do this would be to write a small program (possibly using uinput, although I don't have much experience automating input with Linux so that may be overkill if there's a syscall for it) and run that program.

**Comment by suabo** [comment]
Since there is no more response on this topic I close this issue.
