### ISSUE TITLE
[Issue] Typeout `"\`"` doesn't work

### ISSUE THREAD

**Issue by Ginden** [JSubelj/g910-gkey-macro-support#56]
**Describe the bug**

My config includes:

```
    "g1": {
        "hotkey_type": "typeout",
        "do": "`"
    },
```

When I press G1, it types out: `§ ` (`§` character followed by space).

If I change `G1` to any other string, eg. `foobar`, it works correctly.

**To Reproduce**

**Expected behavior**

I expected backtick to be typed out.

**Screenshots**

**Additional info**

Logs:
```
2022-01-19 13:14:02,483 [INFO] {lib.functionalities.gkey_functionality} - g1 pressed, typing out: '`'
```

Running as service.

Complete config:

```
{
    "__comment": "following hotkey types are supported: nothing, typeout, shortcut and run; only en and si keyboard mappings are currently supported",
    "keyboard_mapping": "si",
    "g1": {
        "hotkey_type": "typeout",
        "do": "`"
    },
    "g2": {
        "hotkey_type": "nothing",
        "do": ""
    },
    "g3": {
        "hotkey_type": "nothing",
        "do": ""
    },
    "g4": {
        "hotkey_type": "nothing",
        "do": ""
    },
    "g5": {
        "hotkey_type": "nothing",
        "do": ""
    },
    "g6": {
        "hotkey_type": "nothing",
        "do": ""
    },
    "g7": {
        "hotkey_type": "nothing",
        "do": ""
    },
    "g8": {
        "hotkey_type": "nothing",
        "do": ""
    },
    "g9": {
        "hotkey_type": "nothing",
        "do": ""
    }
}
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Kernel version
 - Gnome
 - g910-gkeys 0.2.4
 - python 2.7.18 or 3.8.10

**Additional context**

**Comment by Ginden** [comment]
Responsible line:

https://github.com/JSubelj/g910-gkey-macro-support/blob/master/lib/data_mappers/char_uinput_mapper.py#L177

**Comment by JSubelj** [comment]
Hey,

what keyboard do you have set up on your OS and what keyboard mapping do you have setup in your config? If those two don't match then you will have problems with different mapping. You can always write your own mapping for your language or you can use shortcut hotkey type and type out the wanted character.

**Comment by Ginden** [comment]
@JSubelj Changing keyboard mapping to `en` fixed a issue.

Though, it's very surprising behaviour.

As side note - can you review #47 ?
