### ISSUE TITLE
[Issue]typeout in german keyboard layout

### ISSUE THREAD

**Issue by Torpedro1978** [JSubelj/g910-gkey-macro-support#58]
**Describe the bug**
i want to use a  typeout  to output my  email address, the problem is:
I have no way of entering an @ character.

Well the issue is already mentioned inside the example file itself:
`only en, fr and si keyboard mappings are currently supported`
But what is the solution to get the correct key inside this file!
Or even better: Support all keyboards! Why not just output the UTF character?

**To Reproduce**
I have german keyboard selected.
With any editor open the file /etc/g910-gkeys/config.json and add (@ = AltGr + q)
`  "__comment" : "following hotkey types are supported: nothing, typeout, shortcut; only en, fr and si keyboard mappings are currently supported",
  "keyboard_mapping": "si",
`
`"g1": {`
`    "hotkey_type": "typeout",`
`    "do": "user@test.com"`
`  },`
Then i save this file.

**Expected behavior**
When i press G1 it should print 
user@test.com

But in reality it prints („ instead of @)
user„test.com
This is the german representation of AltGr+V, called "Anführungszeichen unten"

I then tried to work around this issue, installed SI keyboard layout and entered the \ from the sI Keyboard - here it is in the AltGr + v. I thougt i just interchange this and i'm done!
Wrong! When i try to enter this `@„` in my file with SI Leyboard active  i get even stranger:

in SI : @„   <- it looks good 
in DE: „ſ   <- switching to de keyboard PANIC

O i have now way of telling the software that i want a german @ singn typed out!

**Screenshots**

**Additional info**
 - did you run in daemon or normal mode
 - logs from /var/log/g910-gkeys.log
 - logs from jurnalctl -u g910-gkeys
 - configuration in /etc/g910-gkeys/config.json

**Desktop (please complete the following information):**
 - OS: Ubuntu 22
 - Kernel version Ubuntu 5.15.0-46.49-generic 5.15.39
 - desktop enviroment Gnome
 - g910-gkeys version latest
 - python version Python 3.10.4

**Additional context**

**Comment by suabo** [comment]
I added support for german keyboard layout. Here is the Link to the [pull request](https://github.com/JSubelj/g910-gkey-macro-support/pull/59).

You have to change the layout after installing to `de` in your config file `/etc/g910-gkeys/config.json`
