### ISSUE TITLE
[Misc] Another keyboard driver example with root daemon & user-side settings/actions

### ISSUE THREAD

**Issue by braoult** [JSubelj/g910-gkey-macro-support#75]
I am sorry, I switched my G910 for a Corsair K70, so I won't be involved in this project anymore.

However, the [K70 has also a driver](https://github.com/ckb-next/ckb-next) (written in C) similar to g910-gkey-macro-support.

The interesting point is that this driver uses a design that [I proposed for the G910](https://github.com/JSubelj/g910-gkey-macro-support/issues/13#issuecomment-1308919383): A minimal **root daemon**, which only purpose is the communication between the device and a **user client**. The client is responsible for everything: settings, actions, animations, etc... There is no risk (and no way) to run any code as root with that system.

Maybe such a design for the Logitech keyboards could solve some current issues and reduce security risks ?

Another topic, I wonder if the [`G15` kernel support](https://github.com/torvalds/linux/blob/master/drivers/hid/hid-lg-g15.c) could be of some use here.

Anyway, thanks a lot for the great job for Logitech keyboards !

**Comment by suabo** [comment]
Thank you for this information.
I'm currently preparing an update to 0.4.0.

With this new version there is no more need to run the service as root and it will setup on default on user level. The config file is also moved to the users home directory to allow different configs on a multi user system.

Hope your happy with your new keyboard!
