### ISSUE TITLE
System Service crashes while booting ...

### ISSUE THREAD

**Issue by schoenid** [JSubelj/g910-gkey-macro-support#77]
**Describe the bug**
If the service gets started with: `systemctl start g910-gkeys`, then it's working.
If the service is enabled with: `systemctl enable --now g910-gkeys`, then nothing happens after login.
`systemctl status g910-gkeys` reports, that the service was haltet wit core dumped ... whatever this means, it's crashed.

With: `systemctl start g910-gkeys`, the service starts normally and it's working fine.

**To Reproduce**
1. Install OS freshly
2. Install the service
3. Look, what happen's ...

**Expected behavior**
Setup, reboot, working.

**Additional info**
Workaround:
I've added some further parameters to g910-gkeys.service ... now it's working rock stable.

```
[Unit]
Description=Support for Logitech g910 keyboard gkeys
Documentation=https://github.com/JSubelj/g910-gkey-macro-support/wiki

Wants=network.target
After=syslog.target network-online.target

[Service]
Type=simple
ExecStart=/usr/bin/env g910-gkeys
TimeoutStopSec=5
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
```
Maybe this could be added to the package too?
The Issue could then be closed.

**Desktop (please complete the following information):**
```
Betriebssystem: Ubuntu Studio 22.04
KDE-Plasma-Version: 5.24.7
KDE-Frameworks-Version: 5.92.0
Qt-Version: 5.15.3
Kernel-Version: 5.15.0-69-lowlatency (64-bit)
Grafik-Plattform: X11
Prozessoren: 16 × 13th Gen Intel® Core™ i7-13700K
Speicher: 62.6 GiB Arbeitsspeicher
Grafikprozessor: llvmpipe
Keyboard: Logitech G910 Spectrum
```

**Additional context**
There were some python warnings (deprecated ...), while installing ... but it's working anyway ...
g910-led works fine, but I have to press M1 (or any other M#) to activate the LED on it.

**Thanks**
Thank you for this service :) , it's great !!!
Now even my multimedia keys are working, which was not the  case before :))

**Comment by suabo** [comment]
Thank you for the contribution.
I'll add the lines to the g910-gkeys.service file in the next release.

> There were some python warnings (deprecated ...), while installing ... but it's working anyway ...
g910-led works fine, but I have to press M1 (or any other M#) to activate the LED on it.

I removed the integration of g910-led and added the signals for activating the leds on the memory keys, so it'll work for everyone.

Hope I'll find some time soon to get the next release out. There are a lot of improvments in terms of performance and usb device handling. So be sure to watch out for the update.
